name: Crawl Data at 630

on:
  schedule:
    - cron: '30 14 * * *'

jobs:
  crawl:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout Repository
      uses: actions/checkout@v2

    - name: Set up Python
      uses: actions/setup-python@v2
      with:
        python-version: 3.8

    - name: Install Dependencies
      run: |
        python -m pip install --upgrade pip
         pip install openpyxl requests beautifulsoup4

    - name: Run Crawler
      run: python WebCrawlwe.py
